### PR TITLE
fix(applications): context menu positioning

### LINKED ISSUE #594: Toogle Controls menu on Actor' sheet appears in wrong place
**Describe the bug**  
The context menu for action, items etc appears in wrong place

**To Reproduce**  
_Steps to reproduce the behavior:_
1. _Go to actor sheet
2. _Click on actions tab
3. _Click on "+" - add equipment action
4. _Close new Window
5. _Click three dots next to new Action. "Toogle Controls"

**Expected behavior**  
Toogle controls appears next to Items (Actions etc)

**Screenshots**  
_If applicable, add screenshots to help explain your problem._

**Foundry VTT Version**  
Foundry V13.350

**Cosmere RPG System & Module Versions**  
CosmereRPG - 2.0.1

**Browser**  
Firefox last Version
Ubuntu
Resolution - 1920x1080 

**Checklist:**
- [ x ] I have searched the existing issues to ensure this bug has not already been reported

https://github.com/user-attachments/assets/ce7db02f-50d6-453b-b970-0649299071b8

### PR DESCRIPTION
**Pull request by stanavdb**
**Type**  
- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Other (please describe):

**Description**  
Fixes issues with AppContextMenu helper causing the context menu to be positioning incorrectly. To resolve this the element binding was moved to the application level (was previously on the context menu parent, which was almost always a component). This change also means context menus can now properly overflow the application bounds, without getting cut off by overflow styling on inner components.

Additionally, this PR also makes it so only 1 context menu can be expanded for a given application at any time (opening a context menu closes all others for that application). And if the parent element if the context menu loses visibility (e.g. changing tabs), the context menu is closed. 

Finally, this PR also updates three components (connections-list, goals-list, injuries-list) to use the AppContextMenu, instead of defining their own context menu behaviour.

**Related Issue**  
Closes #594 

**Related Bugs Post**
https://discord.com/channels/1299110557689053264/1436075858891903038

**How Has This Been Tested?**  
1. Create actor
2. Add action to actor
3. Navigate to actions tab
4. Toggle controls
5. Ensure context menu open in the right location
6. Change tab
7. Ensure context menu closes
8. Add enough actions to actor to exceed sheet size 
9. Toggle controls on last visible action
10. Ensure context menu extends beyond sheet bounds
11. With context menu open, scroll actions list
12. Ensure context menu is closed 
13. Open goals tab
14. Add goal
15. Toggle controls on goal
16. Ensure context menu appears in right location
17. Click "Edit"
18. Ensure the goal sheet opens
19. Click "Remove"
20. Ensure the goal is removed
21. Add connection
22. Toggle controls on connection
23. Ensure context menu appears in right location
24. Click "Edit"
25. Ensure the connection sheet opens
26. Click "Remove"
27. Ensure the connection is removed
28. Open effects & conditions tab
29. Add injury
30. Toggle controls on injury
31. Ensure the context menu appears in right location
32. Click "Edit"
33. Ensure the injury sheet opens
34. Click "Remove"
35. Ensure the injury is removed
36. Open talent tree item
37. Toggle edit mode
38. Right click node
39. Ensure context menu appears in right location

**Screenshots (if applicable)**  
image
image

**Checklist:**  
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes do not introduce any new warnings or errors.
- [x] My PR does not contain any copyrighted works that I do not have permission to use.
- [x] I have tested my changes on Foundry VTT version: 13.350

### CODE REVIEW

File: src/system/applications/actor/components/character/connections-list.ts [hunk 1]
```diff
@@ -106,45 +66,38 @@ any> {
...
-        if (this.contextConnectionId !== null) {
-            // Remove the connection
-            await this.application.actor.deleteEmbeddedDocuments(
-                'Item',
-                [this.contextConnectionId],
-                { render: false },
-            );
+        const connectionId = $(element).closest('.item[data-id]').data('id') as
+            | string
+            | undefined;
```
Comment (zithith) [inline src/system/applications/actor/components/character/connections-list.ts]:
```suggestion
        const connectionId = element.querySelector('.item[data-id]')?.getAttribute('data-id');
```
Please can we start thinking about avoiding jQuery? This native line is just as good (and doesn't need a cast)

File: src/system/applications/actor/components/injuries-list.ts [hunk 2]
```diff
@@ -117,48 +76,41 @@ any> {
...
-
-            // Show injury sheet
-            void injury.sheet?.render(true);
+    public static onEditInjury(
+        this: ActorInjuriesListComponent,
+        element: HTMLElement,
+    ) {
+        const injuryId = $(element)
+            .closest('.item[data-item-id]')
+            .data('item-id') as string | undefined;
```
Comment (zithith) [inline src/system/applications/actor/components/injuries-list.ts]:
```suggestion
        const injuryId = element.querySelector('.item[data-item-id]')?.getAttribute('data-item-id');
```

**Review by zithith — COMMENTED** [review]
So the general implementation and refactor is great, fixes the bug and makes the menus much better 👍 

Just have a couple of comments re: DOM querying. TBH my suggestions could also get turned into a util function somewhere, such as:
```js
function getClosestInstanceOfDataAttribute(start: HTMLElement, attribute: string) {
  return start.closest(`[data-${attribute}]`)?.getAttribute(`data-${attribute}`);
}
```

**Review by zithith — APPROVED** [review]
